### ISSUE TITLE
JaniDrobe (and maybe others) can make items disappear

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#10742] opened 2020-12-27 20:29 UTC
- if I put the bought space cleaner back into it, then it disappears forever.

**Comment by ToGWtF** [comment] 2020-12-27 20:31
https://github.com/yogstation13/Yogstation/issues/9251

**Comment by redmoogle** [comment] 2021-01-10 16:41
Duplicate of #9251 just moving it there

**Closed as completed by redmoogle** 2021-01-10 16:41 UTC
