### ISSUE TITLE
Ashwalkers can Fulton

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#8264] opened 2020-04-25 04:05 UTC
As title.

**Comment by BOBsHERE** [comment] 2020-04-26 22:43
Thats actually amazing.

**Comment by overlord12345** [comment] 2020-04-27 00:32
Not a bug, theres no reason a ashwalker would not understand fultoning

**Comment by MegaEmpirical** [comment] 2020-04-27 02:29
The entire point of their change was to keep them off the station.

https://github.com/yogstation13/Yogstation/pull/6953

**Comment by jcatjmeow** [comment] 2020-06-28 16:33
This isn't a bug. Make a forum post about it if you want it added.

**Comment by JamieD1** [comment] 2020-06-29 15:23
Oversight missed in original PR, Jcat didnt do anything wrong by closing this, perhaps it  should of been labelled as an oversight instead or actioned as such. If you have questions in future ask a HC.

**Comment by MegaEmpirical** [comment] 2020-06-29 15:26
HC told me to post it!

**Closed as completed** 2020-07-03 13:05 UTC
