### ISSUE TITLE
Crew monitor has incorrect colors on status

### ISSUE THREAD

**Issue by redmoogle** [yogstation13/Yogstation#8827] opened 2020-06-06 13:05 UTC
Issue reported from  Round ID: 29905 (Yogstation 13)

Reporting client version: 513.1522

Self-Explanatory
Could have something to do with new tgui

![image](https://user-images.githubusercontent.com/20369082/83944875-c0eec400-a7d4-11ea-8dd6-d984d8fffc7a.png)

**Comment by Firewolf34** [comment] 2020-07-02 05:37
This bug did not exhibit itself last round (round 30368) but I have seen it happen in the past 2 weeks. May be a spurious issue (likely) or possibly was fixed very recently (less likely)

**Comment by adamsong** [comment] 2021-07-05 16:14
Anyone able to reliably reproduce this?

**Comment by redmoogle** [comment] 2021-07-05 16:25
> Anyone able to reliably reproduce this?

I haven't seen it happen again when I still played

**Comment by adamsong** [comment] 2021-07-06 12:46
Closing as unable to reproduce

**Closed as completed by adamsong** 2021-07-06 12:46 UTC
Labels: Bug, Issue - Needs Confirmation
