### ISSUE TITLE
 Toggling Auto-Observe as a ghost still makes space turn white

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21452] opened 2024-02-18 23:44 UTC
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Caused by #21221

 Submitted by: masterdrake (598557108551811073)

**Comment by AMyriad** [comment] 2024-03-25 02:29
duplicate of #21333

**Closed as completed by AMyriad** 2024-03-25 02:29 UTC
Labels: Duplicate
