### ISSUE TITLE
Super Fast Speed with Cardboard box

### ISSUE THREAD

**Issue by MarcosPauloMarques** [yogstation13/Yogstation#5150] opened 2019-04-20 08:31 UTC
## Reproduction:Force the cardbox movement to the corners while touching a wall. I've seen there are plenty of threads about this, but none this year. So i'm leaving it here.

![image](https://user-images.githubusercontent.com/18073899/56454858-78a0e800-632d-11e9-813f-6cc6bb12cc98.png)

**Comment by MegaEmpirical** [comment] 2019-04-20 13:33
This hasn't been fixed yet? Thought it had been.

**Comment by HomocidlePancakes** [comment] 2019-04-20 17:39
Never was fixed. Also fucking newfffffffff... FRIENDS re-reporting known bugs

**Comment by Altoids1** [comment] 2019-04-22 19:33
Dupe of #2324 . Closing.

**Closed as completed by Altoids1** 2019-04-22 19:33 UTC
