### ISSUE TITLE
space ninja: mining combat injectors don't inject.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#13167] opened 2022-01-26 07:46 UTC
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: Injector pens work on space ninjas, however the combat injectors on mining don't work without taking the suit off and exposing flesh.
 Submitted by: Rg4 (185114950354731008)

**Comment by Xoxeyos** [comment] 2022-01-28 03:56
I was able to reproduce this issue. https://www.youtube.com/watch?v=Rf3lLFd0Rg0

**Comment by SomeguyManperson** [comment] 2022-06-20 20:12
oh right for some reason hyposprays check thick clothing, unsure if this is intended orn ot

**Comment by Oblisk234** [comment] 2024-12-27 00:33
Likely fixed by #15492, either way mining hypospray working.

**Closed as completed by Oblisk234** 2024-12-27 00:33 UTC
