### ISSUE TITLE
xenos are unable to whisper to people

### ISSUE THREAD

**Issue by LassiH** [yogstation13/Yogstation#22901] opened 2024-12-31 00:11 UTC
### Severity

Inconvenience

### Short Description

trying to whisper to people as xeno bluescreens the whisper panel

### Reproduction

1 be xeno
2 try to whisper to person
3 get ntos death screen

### Round ID

#54899

### Test Merges

#22095 #22813 #22802

### BYOND Username

LassiH

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by Oblisk234** [comment] 2024-12-31 03:36
Duplicate of #21456

**Closed as not planned by Oblisk234** 2024-12-31 03:36 UTC
Labels: Duplicate
