### ISSUE TITLE
Eye and hair color locked to black?

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#8392] opened 2020-05-05 17:18 UTC
## Reproduction:
I experienced this myself on my first private Yogs server, which I'm led to believe, from my short experience there, can be pretty jank in any event, but before that I got a mentor ticket regarding the same issue.
"Wrathias62: Any clue why my character can't have any hair colour other than black?"
I can't speak for the exact experience of the unfortunate new player, but for me, I was trying to set up my character menu for the first ("first") time, and it all worked fine up to trying to change eye and hair color. As soon as I changed either from the randomized default, it jumped to #000000, when I was going for blonde-hair-blue-eyes. I tried again, made absolutely sure I was picking the colors I wanted, and it saved again as #000000. Pitch-black, blended in with the character customization background.
I spent six hours playing God with void hair, I couldn't find a workaround.

**Comment by jcatjmeow** [comment] 2020-06-26 16:43
was unable to reproduce but I'll keep at it

**Comment by jcatjmeow** [comment] 2020-07-11 01:49
Yeah, I can't reproduce this. I have a feeling it is related to your setup in some way. The only thing I can suggest is to update your branch and reset all your config and files and such.

Since this isn't happening on the server itself, I'm closing this

**Closed as completed by jcatjmeow** 2020-07-11 01:49 UTC
Labels: Issue - Needs Confirmation
