### ISSUE TITLE
 Map Gen Does Not Work

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#17475] opened 2023-01-13 07:18 UTC
## Test Merges: 
Not Supplied / None
## Reproduction:
The usual fix griefer button still does not work. The one being Repair: Reload Block - Mass Delete - In Place.

 Submitted by: Hisakaki (98481061960351744)

**Comment by ThatLing** [comment] 2023-01-13 08:20
Duplicate of https://github.com/yogstation13/Yogstation/issues/17282

**Closed as completed by ThatLing** 2023-01-13 08:20 UTC
Labels: Bug, Duplicate
