### ISSUE TITLE
Botany reactions misfiring

### ISSUE THREAD

**Issue by MaulJunior** [yogstation13/yogstation#810] opened 2016-09-17 17:46 UTC
When preparing Plant-Grenades (Chemicals built into the Plant, Liquid Contents for squishing on arrival), some reactions take place only when the plant is harvested.

I have not tested other reactions, but I just tested Sugar+Phosphorus+Potassium (Smoke), and the instant I harvested the tomatoes (for liquid contents and vegetative smoke grenades upon splatter), smoke appeared around the plant tray the tomatoes were harvested from.

The Tomatoes from the plant were lying on the floor and in the Plant Bag. When I threw the Tomatoes at the wall, they just went squish. No smoke. Which was, you know, kind of the whole point. clouds of Ammonia fertilizer smoke, clouds of Weed Killer for anti-Kudzu etc.

**Comment by Cruix** [comment] 2016-09-17 22:20
This is intended behavior. The reagents in the tomato were completely used up in the smoke when you harvested the plant, so there was nothing in them to react.

**Comment by ShadowDeath6** [comment] 2016-09-17 23:53
>get smoke components + omnizine in one plant
harvest
makes smoke but is only left with omnizine with no omni in smoke

**Comment by Cruix** [comment] 2016-09-18 00:19
That's probably because the omnizine was added to the fruit after the smoke chemicals due to the order of the genes. That could probably be fixed with some minor refactoring of plant code. We could also make it so the squish gene makes reactions not happen until the squish happens.

**Comment by MaulJunior** [comment] 2016-09-18 07:09
so you have to worry about the order of the chemicals? That seems......overly complicated.


The reaction after squish part would be amazing if you could make it happen.

**Comment by Cruix** [comment] 2016-09-28 16:43
Looking at the code, there is a specific gene called Separated Chemicals that does exactly what we are talking about. No plant seems to carry it by default.

**Closed** 2016-12-21 22:49 UTC
