### ISSUE TITLE
Yogstation graphics settings are not saved.

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#9210] opened 2020-07-13 21:24 UTC
- For example, you're using widescreen, and the game cannot save 1.5x zoom in the settings. It always starts pixel perfect, not remembering the chat area size, always need to re-adjust that, too.

**Comment by adamsong** [comment] 2021-07-05 15:57
Duplicate of #9789

**Closed as completed by adamsong** 2021-07-05 15:57 UTC
Labels: Bug
