### ISSUE TITLE
Sometimes the hulk gene isn't expressed

### ISSUE THREAD

**Issue by TristanSaucy** [yogstation13/yogstation#2042] opened 2017-03-24 17:50 UTC
Chameleon was 1, hulk was 2. By themselves they would be expressed but when paired together hulk would not be expressed but chameleon would be.

**Comment by Cruix** [comment] 2017-03-24 17:57
Dupe of https://github.com/yogstation13/yogstation/issues/2039

**Closed by Cruix** 2017-03-24 17:57 UTC
