### ISSUE TITLE
Sprites bugging out after our 513 update

### ISSUE THREAD

**Issue by Hopekz** [yogstation13/Yogstation#8417] opened 2020-05-07 05:44 UTC
The game randomly decides "okay; everyone's side sprite is now a black box the size of your screen"
Has happened to me 3 separate times so far on 3 separate shifts last week

@alexkar598 

Asked around. 
This seems to happen to people every few rounds.

My face being a box

![PimBGvFC0u](https://user-images.githubusercontent.com/24533979/81258592-9fdf5b80-8ffb-11ea-874f-847dece88e49.gif)

CE facing the side direction gives the same box
![dreamseeker_UQ7tl8Ye5W](https://user-images.githubusercontent.com/24533979/81258505-732b4400-8ffb-11ea-93c5-6e845f7151fb.png)

**Comment by alexkar598** [comment] 2020-05-07 12:45
byond bug. will get fixed eventually

**Comment by Rayisken** [comment] 2020-05-11 14:57
Is there an applicable workaround you can provide or facilitate since we do not have an immediate timeline for the fix to be released?

**Comment by jcatjmeow** [comment] 2020-06-26 16:42
duplicate of #8684 
Byond bug. Not something we can help with

**Comment by jcatjmeow** [comment] 2020-06-29 22:02
fixed

**Closed as completed by jcatjmeow** 2020-06-29 22:02 UTC
Labels: wontfix
