### ISSUE TITLE
hop can't access custodial closet, at least on yogstation

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#2482] opened 2018-09-08 18:15 UTC
[Round ID]: #18400

[Reproduction]: # Be HoP, attempt to open custodial closet

**Comment by Ktlwjec** [comment] 2018-10-12 16:15
Can't reproduce this.

**Comment by Altoids1** [comment] 2019-02-22 20:26
Checked the code myself, problem was solved eventually. Closing.

**Closed as completed by Altoids1** 2019-02-22 20:26 UTC
Labels: Bug, Mapping
