### ISSUE TITLE
[Bug...?] The Paradox of the Atmospherics Plasmaman

### ISSUE THREAD

**Issue by Robertruler77** [yogstation13/yogstation#364] opened 2016-07-14 19:42 UTC
**Problem at Hand.**

Plasmamen are extremely vunerable to oxygen when the plasmaman specific helmet is not on. 
However, don the atmospherics hardsuit AND put the helmet on, and you will be set on fire but take NO damage.
The eternal paradox must be rectified.

Steps to reproduce:
1. Be Plasmaman in Atmos
2. Don atmos helmet and hardsuit whilst still breathing plasma
3. Laugh as you are now a fireproof but fire dealing being that can screw up the day of anyone who doesn't want to be set on fire.

**Comment by ParagonPrime** [comment] 2016-07-14 21:18
featurefeature_feature_

I want to be able to assassinate my targets as a plasmaman atmos tator **without ever laying a finger on them, just standing on top of them and eternally burning**

**Comment by Super3222** [comment] 2016-07-18 00:03
Not a bug, it's a feature.

**Comment by Robertruler77** [comment] 2016-07-18 08:34
Alright, i am okay with this.

**Comment by Greatbigben** [comment] 2016-07-20 23:28
close this bby

**Closed** 2016-08-28 03:53 UTC
