### ISSUE TITLE
nukedisk visible through ai static

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#12749] opened 2021-11-25 03:24 UTC
## Test Merges: 
Not Supplied / None
## Reproduction:
Severity: 
Desc: Nuke Disk is visible through the static of an area with no cameras
 ## Supplied Image:

![SuppliedImage](https://cdn.discordapp.com/attachments/773277250090434640/913268813158555648/unknown.png)
 Submitted by: The Lusty E (302595577793740801)

**Comment by bruhlookatthisdood** [comment] 2021-11-25 03:26
Fuck, I accidently posted too early, I will make another report properly.

**Comment by adamsong** [comment] 2021-11-25 03:34
Duplicate of #12750

**Closed as completed by adamsong** 2021-11-25 03:34 UTC
