### ISSUE TITLE
 chasms ignore jaunters

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21577] opened 2024-03-01 20:37 UTC
## Test Merges: 
Not Supplied / None
## Reproduction:
chasms ignore jaunters

 Submitted by: snoobper (1079798074068709386)

**Comment by AMyriad** [comment] 2024-03-16 17:39
might've been fixed in #21645, also this is a duplicate of #21487

**Comment by ToasterBiome** [comment] 2024-03-22 01:30
fixed in https://github.com/yogstation13/Yogstation/pull/21645

**Closed as completed by ToasterBiome** 2024-03-22 01:30 UTC
