### ISSUE TITLE
Beret's make you bald

### ISSUE THREAD

**Issue by Rayisken** [yogstation13/Yogstation#972] opened 2018-05-24 13:59 UTC
Beret's have an extra line of flesh that appears when equipped that make you look like you're bald. Kinda annoying as it's a popular donator item choice. Partheo said this a code issue not a sprite issue.

**Comment by ThatLing** [comment] 2018-05-24 14:34
Duplicate of #591

**Closed as completed by ThatLing** 2018-05-24 14:34 UTC
