### ISSUE TITLE
Golems can't use medicine patches

### ISSUE THREAD

**Issue by githubuser4141** [yogstation13/Yogstation#9296] opened 2020-07-23 08:22 UTC
[Round ID]: 30176

## Reproduction: Spawn as a free (adamantine) golem. Assuming you're in the free golem ship, observe the rows of medical kits you start off with, apparently to use if you're injured. Try to use one of the patches, it will say the golem has no exposed skin or flesh.

Issue: Golems (I only checked with adamantine, but the others are probably the same) can't use patches even though they start with boxes full of patches. This also makes the brute first aid kit golems can buy from their vendor mostly useless.

**Comment by SomeguyManperson** [comment] 2020-07-23 17:14
@Hopekz

**Comment by overlord12345** [comment] 2020-07-25 14:09
I think this was intended

**Comment by Ratvar** [comment] 2020-07-25 14:37
more of mapping issue, golem vendor was not changed when patches stopped working on thick skinned things

**Comment by jcatjmeow** [comment] 2020-07-25 18:32
Not a bug.

It is an oversight, however

**Comment by UselessTheremin** [comment] 2021-04-29 13:32
fixed in this https://github.com/yogstation13/Yogstation/pull/9968

**Closed as completed by UselessTheremin** 2021-04-29 13:32 UTC
Labels: Issue - Confirmed, Issue - Low priority
