### ISSUE TITLE
Yogpubby map does not give Sigtech relevant access

### ISSUE THREAD

**Issue by camoceltic** [yogstation13/Yogstation#6677] opened 2019-09-04 05:40 UTC
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Just start as sigtech on the Yogpubby map.  I've only been Sigtech on round start, so I haven't tested if it's an issue joining mid-round.

The ID you are issued seemingly lacks all access except Telecomms, so you can't even access Engineering to go through to the common areas.  There is also a door leading to the console to read PDA messages and set up scripts that you can't access with the default access, so you can't even really do your job outside of making sure that the machinery is in functioning order.

**Comment by MegaEmpirical** [comment] 2019-09-04 10:12
That's not an issue with the ID, it's an issue with the doors. But yeah, still an issue.

**Comment by MayhemSailor** [comment] 2019-09-05 00:23
Hey! See  #6674

**Comment by MegaEmpirical** [comment] 2019-09-05 00:50
I can't tell if that PR fixes this or he's advertising his PR

**Comment by camoceltic** [comment] 2019-09-05 03:09
> That's not an issue with the ID, it's an issue with the doors. But yeah, still an issue.

Yeah.  Either way, bringing attention to it will hopefully get it fixed.

> I can't tell if that PR fixes this or he's advertising his PR

Apparently it fixes this issue (which is actually a duplicate of #5757, which is mentioned in that PR), so eeh?  I don't know why it's being brought up, though.  It's not like me knowing about it helps anything, since it's not like I can contribute to getting the fix implemented.

**Comment by MayhemSailor** [comment] 2019-09-05 13:07
It's a fix for #5757, your issue is a duplicate of that issue.

**Comment by MayhemSailor** [comment] 2019-09-17 20:46
This issue should be closed. Fixed by #6674

**Closed as completed** 2019-10-08 02:05 UTC
Labels: Bug
