### ISSUE TITLE
Blinding white light when you observe

### ISSUE THREAD

**Issue by Therandomhoboo** [yogstation13/Yogstation#21737] opened 2024-03-25 01:18 UTC
### Severity

Inconvenience

### Short Description

Observing people with their UI on makes space look white

### Reproduction

1. Observe a player
2. Turn on view UI
3. Look into the blinding white space

### Round ID

#51974

### BYOND Username

therandomhoboman

### Was this done on a locally hosted or non-Yogstation hosted server?

None

**Comment by AMyriad** [comment] 2024-03-25 02:29
duplicate of #21333

**Closed as completed by AMyriad** 2024-03-25 02:29 UTC
Labels: Duplicate
