### ISSUE TITLE
Despite being antag banned I didnt get force ghosted when converted in rounds 32436 and 32437

### ISSUE THREAD

**Issue by TheLinuxOS** [yogstation13/Yogstation#10115] opened 2020-10-23 02:46 UTC
Pretty much what the title says is the exact issue, I'm not sure what is causing it and was told to create a bug report about it

**Comment by adamsong** [comment] 2021-07-05 17:56
Duplicate of #8307

**Closed as completed by adamsong** 2021-07-05 17:56 UTC
Labels: Bug
