### ISSUE TITLE
Lawyers and the courthouse should play a part in admin tickets

### ISSUE THREAD

**Issue by TristanSaucy** [yogstation13/yogstation#1947] opened 2017-03-09 05:06 UTC
Admins could be judges and lawyers need some type of game-play mechanism related to justice and plus the whole crowd of people would get off on it. You could choose to respawn in some courthouse at round end.

**Comment by Jc1469** [comment] 2017-03-09 08:09
Not a bad idea, it'd take a load off of our already lazy as fuck admins.  We should also remove the ticket system too, seeing we wouldn't really need it. And no.

**Comment by drderp3635** [comment] 2017-03-09 17:18
Absolutely not. 

Are you actually impaired? The admin tickets hold no IC relafence for a reason. If a admin needs more opinions or sides from the player base they will ask them themselves. I'm just hoping this is a joke.

**Comment by Drakkon** [comment] 2017-03-09 23:49
wtf

**Comment by TristanSaucy** [comment] 2017-03-09 23:55
Na its not a joke, lawyers need a gameplay mechanic related to justice. As lawyers stand they are irrelevant. People can already view the peanut gallery in ban appeals, whats the issue with a live version of that? You stated there's a reason why not, but what exactly is that reason? Tickets hold up the round anyways, why not let people view the events?

**Comment by Drakkon** [comment] 2017-03-10 03:26
If we need more in-game entertainment, sure, let's make some more things to pass the time. But that should have nothing to do with the server's rule enforcement.

**Comment by ShadowDeath6** [comment] 2017-03-10 19:44
No, admin enforcement is never an in game issue. I don't even know what situations that this would apply. Every situation I can think of is like "oh a griefer" but only the admins know if he's antag or not and it's giving meta info away to the lawyers every time someone gets in trouble which is stupid

**Comment by Drakkon** [comment] 2017-03-10 19:53
Closest I could think of is bringing back Centom officials and ability of Lawyers to report to Centcom to request one. (Ghost position)

**Comment by Lightning38088** [comment] 2017-03-10 21:19
Centcom officals are different tho they are there for rp purposes since they can cause a ERT being sent in or even a deathsquad.

**Comment by Drakkon** [comment] 2017-03-11 04:28
@Lightning38088 Based off /tg/ I believe there's a "middle" and "upper" management, "upper" having the power to call them in. I believe staff have to be on to confirm officials to be spawned anyways.

**Comment by Mrcreepssss** [comment] 2017-03-16 11:12
i doubt its a good idea, i think it would be kinda fun to see a courtroom RP honestly but i doubt it should be done like this. i do think lawyers need SOME kind of justice mechanic, i think like drakkon said requesting an official could be a good one. an issue is though, lawyers job is RP focused, in a way that takes time, sec usually doesn't have that time, or the verdicts would be shorter than a lawsuit, i think the issue isn't so much a lack of lawyer-mechanics, but a lack of incentive to make use of one.

**Comment by AdamElTablawy** [comment] 2017-03-16 15:18
I hereby nominate this for stupidest idea of the century.

**Comment by Drakkon** [comment] 2017-03-16 18:33
We could put a nicer courtroom on z2.

**Comment by nichlas0010** [comment] 2018-02-04 12:23
why was this not closed as soon as it was made, jesus christ

**Closed by nichlas0010** 2018-02-04 12:23 UTC
Labels: Feature Request
