### ISSUE TITLE
But you ain't go no legs Lieutenant Dan

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#4543] opened 2019-02-22 02:02 UTC
Incapable of doing so fucking much whilst having no legs or non-functional legs. Can't turn PDA light on, can't use consoles, can't use vendors, can't even take the ID out of PDA.

**Comment by Altoids1** [comment] 2019-02-22 03:07
Duplicate of #4432 , closing

**Closed as completed by Altoids1** 2019-02-22 03:07 UTC
Labels: Bug

**Comment by MegaEmpirical** [comment] 2019-02-22 03:20
Ah didn't notice that one.
