### ISSUE TITLE
Teleport runes don't function, and neither do portals from bluespace wormhole gens

### ISSUE THREAD

**Issue by ghost** [yogstation13/Yogstation#3778] opened 2018-12-09 02:14 UTC
They don't. You use them and they don't work. You do not move or teleport in any way, shape, or form when you activate the rune or attempt to step through the portals.

**Comment by monster860** [comment] 2018-12-10 17:04
I opened 2 prs on tg station to fix both issues and they got merged there and got merged here. So this issue should be fixed now.

The problem with teleport runes is they teleported from the source to the source.

Portals? THe portals are dense, so you Move() to the portal, bumping it, so it teleports back, bumping the original portal, and so on for ever.

Both issues are caused by different things but were caused by the same PR. In one PR, some idiot tg coder managed to singlehandedly fuck over almost every form of 2-way teleportation except for quantum pads.

**Closed as completed** 2018-12-11 15:36 UTC
