### ISSUE TITLE
Chemistry Leporazine is broken

### ISSUE THREAD

**Issue by AAAbattery** [yogstation13/yogstation#468] opened 2016-08-04 22:01 UTC
It does not seem to work. As a chemist I took a 40u pill of leporazine then set myself on fire. I promptly burned to death despite the fact that the leporazine should have made me immune to temperature damage for a short time.

**Comment by Yackitori** [comment] 2016-08-04 22:28
You still take fire damage from the actual fire if I'm not mistaken.

**Comment by AdamElTablawy** [comment] 2016-08-04 23:41
It stops temperature change, and it also doesn't negate it completely. It stabilizes it quickly but it can be outpaced.

Fire outpaces it.

Also, you SET YOURSELF ON FIRE. No temperature change is not going to change the fact that your SKIN IGNITING AND MELTING LIKE A HUMAN CANDLESTICK is probably going to sting a bit.

**Comment by X-TheDark** [comment] 2016-08-05 05:29
Actually, fire itself does 0 damage, it's, indeed, the temperature damage that gets you.

Your temperature, without any thermal protection is modified as follows:
`bodytemperature += (30 + (fire_stacks * 12))`
whereas leporazine stabilizes at this rate:
`M.bodytemperature = max(310, M.bodytemperature - 60)`

For example, if I set myself on fire while there's plasma around me (hit Xenobiology plasma sheet with welder), I'm set on fire and get 10 stacks of fire on me, so my body temperature would still increase at a rate of **90 degrees per tick** (disregarding fire_stacks decreasing a little bit each tick)...and considering your safe body temperature is 310 +/- 50...you see how you still get really, really burned up even though you have leporazine...

**Comment by AAAbattery** [comment] 2016-08-08 04:35
Before leporazine made you completely fire-proof for as long as the drug was in effect. However, now leporazine does NOTHING, and there was no patch note so I am assuming it is a bug.

**Comment by X-TheDark** [comment] 2016-08-08 05:24
The reason for this are rebase things, /tg/ made the fire temperature change MUCH more potent, as in
Pre-rebase:
`bodytemperature += BODYTEMP_HEATING_MAX (which is 30)`
Post-rebase:
`bodytemperature += (BODYTEMP_HEATING_MAX + (fire_stacks * 12))`

So, /tg/ added the fire_stacks affecting your temperature, and now it can actually increase faster than leporazine can decrease it (which never happened in old code, since 60 > 30, always (obviously)).

**Comment by EMT321** [comment] 2016-10-04 11:35
@Cruix Can this issue be closed? It appears resolved in some form.

**Comment by X-TheDark** [comment] 2016-10-04 14:21
Not resolved, but definitely not a bug, this just doesn't make you immune to fire anymore. Feel free to comment further if this actually needs to be implemented.

**Closed by X-TheDark** 2016-10-04 14:21 UTC
Labels: Balance / Rebalance, Feature Request
