### ISSUE TITLE
Z-Level Travel/Chasms on IceMeta Broken

### ISSUE THREAD

**Issue by CrazyDrakkon** [yogstation13/Yogstation#21342] opened 2024-01-31 03:03 UTC
### Severity

Round Breaking

### Short Description

Traveling from z-level to z-level is disabled and chasms are strange on IceMeta 

### Reproduction

1. Exist on Icemeta

### Round ID

Round #51297

### Test Merges

#21008 #21266

### BYOND Username

crazy_drakkon

### Was this done on a locally hosted or non-Yogstation hosted server?

No

### Additional information

Chasms leading to VR z-level
![image](https://github.com/yogstation13/Yogstation/assets/18729830/3f9bf314-2422-4a52-93f4-7dbbdc593880)

Station z-level chasms to plasma river gone
![image](https://github.com/yogstation13/Yogstation/assets/18729830/9a1ec082-2a76-42a9-85dd-8667a556e11b)

Mining stairs gone
![image](https://github.com/yogstation13/Yogstation/assets/18729830/6124c099-5dd9-4e98-9a38-81c378be140d)

**Comment by AMyriad** [comment] 2024-03-17 21:50
this is 100% an issue with #21266
currently not merged so I wouldn't be able to tell what the problem is as of now :p

**Comment by ToasterBiome** [comment] 2024-06-18 20:07
No longer an issue

**Closed as completed by ToasterBiome** 2024-06-18 20:07 UTC
