### ISSUE TITLE
Egun with only 6 shots

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#3981] opened 2018-12-28 03:37 UTC
Round 20438. Admin had no idea why an egun had only 6 laser shots at full capacity.

**Comment by Altoids1** [comment] 2019-02-10 22:35
That was probably an IC issue caused by you not noticing some adminbus or you lagging slightly.

If this was *actually* a code issue, I'm thinking it could be, uh:
- You were clicking so hard that some of the fire commands were not fully processed or even sent to the server. Do you use macros?

**Comment by 00aquir** [comment] 2019-02-11 11:53
It used to happen to others, too, when a gun (sometimes even the gun they spawned with), which hasn't suffered EMP or anything, at one point gets decreased amount of shots and the admins don't know why it happens. It did it also when it was being fired slowly, using simply the mouse 1 input.

**Comment by Altoids1** [comment] 2019-04-18 01:20
Closing until someone can reproduce this.

**Closed as completed by Altoids1** 2019-04-18 01:20 UTC

**Comment by 00aquir** [comment] 2022-07-23 06:42
It came a long way, this time with only 5 disabler shots https://github.com/yogstation13/Yogstation/issues/14959
