### ISSUE TITLE
Can't see pill/bottle icons in chemmaster

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#5110] opened 2019-04-13 00:57 UTC
Unsure if this is currently occurring elsewhere, wardrobe seemed fine.

![image](https://user-images.githubusercontent.com/36208065/56072507-9f778100-5d65-11e9-8802-5dbba912ce68.png)

**Comment by Putnam3145** [comment] 2019-04-13 03:32
Sort of duplicate of #4894, but it's not a delta-only problem

**Closed as completed** 2019-07-08 17:47 UTC
Labels: Bug, Sprites
