### ISSUE TITLE
Holoparasites can still damage-lock you despite the nerf.

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#11489] opened 2021-05-17 21:07 UTC
## Test Merges: 
Not Supplied / None
## Reproduction:
Round: 35381
Round Time: 00:20:00 - 00:27:00
Nukie holoparasites were still able to damage lock me despite them being nerfed. Not sure if it was because there were two of them or not but it's still fricking bullcrap.
 Submitted by: DukeBobRoss II Phone Bank Lord (305348676883316737)

**Comment by UselessTheremin** [comment] 2021-05-25 14:50
this was discussed in the development channels a few days ago, and you were stunlocked by TWO holoparasites, not one, so it's a feature not a bug. if you have complaints on me closing this, dm me on discord at Theremin#3676

**Closed as completed by UselessTheremin** 2021-05-25 14:50 UTC
