### ISSUE TITLE
Quiet Mode Defaults to Off Every Roundstart

### ISSUE THREAD

**Issue by FatalEYES** [yogstation13/Yogstation#9782] opened 2020-09-24 11:29 UTC
Issue reported from  Round ID: 31934 (Yogstation 13 (Main))

Reporting client version: 513.1525

Title.

**Comment by redmoogle** [comment] 2020-11-10 22:05
Duplicate of: https://github.com/yogstation13/Yogstation/issues/9416

**Closed as completed by redmoogle** 2020-11-10 22:05 UTC
Labels: Bug
