### ISSUE TITLE
Issue with "antag rolling abuse" and blood brother

### ISSUE THREAD

**Issue by Ktlwjec1** [yogstation13/Yogstation#8370] opened 2020-05-02 06:48 UTC
Round 29160 this happened, there's been more examples previously but I wouldn't know the round numbers exactly.

So:
Blood brother gamemode.
Blood brother 1 (AI): "x just got booted back to lobby with no jobs, but antags enabled."
Blood brother 2 (bartender): Still spawns as their blood brother. But gets the message "You are the Blood Brother of ." Blood brother 1 appeared to get the antag messages from the lobby.
Blood brother 1 joins the round later and still has the blood brother status according to the admin antag panel.
I asked and blood brother 1 said they couldn't see they are a blood brother during the round.

**Comment by boodaliboo** [comment] 2020-05-05 22:46
i dont understand what this means

**Comment by jcatjmeow** [comment] 2020-06-26 16:45
I do understand what this means. But I can't reproduce it 😩

**Comment by adamsong** [comment] 2021-06-27 16:06
This issue is caused because they will roll antag, and then not have any valid jobs available with roll random job disabled. Similar things happen in other antags, but not all.

**Comment by adamsong** [comment] 2021-07-05 17:49
Duplicate of #5182

**Closed as completed by adamsong** 2021-07-05 17:49 UTC
Labels: Bug, Issue - Needs Confirmation
