### ISSUE TITLE
tgui breaks and cant reopen

### ISSUE THREAD

**Issue by redmoogle** [yogstation13/Yogstation#8894] opened 2020-06-13 23:33 UTC
TGUI cant reopen once open, only happens on yogstation and not private servers
Round ID: N/A(30047 if you're gonna pester me)

**Comment by ToGWtF** [comment] 2020-06-14 17:30
I have a similar problem when I am on two servers at once

**Comment by jcatjmeow** [comment] 2020-07-11 01:45
unable to reproduce, although I didn't try two servers at once.

I think this is fixed by now? Not sure. I think it's been fixed. @ me if you experience this bug still and I will reopen this

**Closed as completed by jcatjmeow** 2020-07-11 01:45 UTC
Labels: Bug
