### ISSUE TITLE
Slime People and Shadow People are invisible

### ISSUE THREAD

**Issue by AndySok** [yogstation13/yogstation#630] opened 2016-08-24 03:28 UTC
When you are using green slime extact on yourself you become invisible and most of your organs dissapear.
Same way if you were Upgraded by a shadowling

# How it should work
>1.You are using green slime extract
>2.you become slimy (light green or light blue)
## Or
>1.you get upgraded by a shadowling
>2.you become dark and you get red eyes

# How it works
>1.You are using green slime extract
>2.you become invisible
## Or
>1.you get upgraded by a shadowling
>2.you become invisible

# How to reproduct

>1.Become scientist
>2.Do xenobiology
>3.Get green slime extract
>4.use it
>5.cry because you are invisible

# OR

>1.be a thrall
>2.ask shadowling to upgrade you
>3.get upgraded
>4.cry

# Screenshots
![problem_1](https://cloud.githubusercontent.com/assets/19246179/17917273/bc9457a0-6988-11e6-87d2-90250541d3c7.png)
![problem_1_2](https://cloud.githubusercontent.com/assets/19246179/17917275/bedd026e-6988-11e6-8f02-dcc2a3d90aeb.png)
![problem_1_3](https://cloud.githubusercontent.com/assets/19246179/17917278/c22f661e-6988-11e6-819a-ca4c82d25e49.png)

**Comment by ShadowDeath6** [comment] 2016-08-24 04:11
THE INVISIBLE MAN RACE BUG IS BACK

**Comment by AndySok** [comment] 2016-08-24 13:49
Yup

**Comment by AndySok** [comment] 2016-08-24 22:21
That's a REALLY bad feature then.

You can really abuse it.
# For example
>Become invibisible on abductors round
>don't get caught by abductors cause they don't see u

## Or
>Shadowling round
>you are invisible
>You are following shadowling everywhere and kill him with lights

## Or
>nuke ops round
>you are invisible
>follow captain and when caps die use some kind of gun on nuke op who killed cap

**Comment by ShadowDeath6** [comment] 2016-08-24 22:22
I abused the old race invis bug, it's not as bad as you think since you can't wear clothes or hold items since it gives you a hitbox, and anyone with a HUD can see you and hit you as well

this still needs to be fixed though

**Comment by AndySok** [comment] 2016-08-25 00:29
It gives your hitbox only for those who have HUD. It literally makes you invincible for anyone without HUD.

Like you can order double-esword and just kill everyone because noone can even hit you.
Well , maybe tazer can

**Comment by ShadowDeath6** [comment] 2016-08-25 02:32
people can just click the double esword or any clothes you wear, it doesn't make you completely invisible, just your skin

**Comment by AndySok** [comment] 2016-08-25 03:01
I was talking about if you make yourself nude
like
last screenshot , i'm nude and only my eyes are visible

**Comment by Super3222** [comment] 2016-08-25 20:02
I'm already looking into this, and I believe I found the reason for the bug.

**Comment by AndySok** [comment] 2016-08-25 21:51
noice

**Comment by Super3222** [comment] 2016-08-27 04:37
Alright, the problem is that slimepeople, jellypeople, and shadowpeople all lack NODISMEMBER.
Which means they require each individual limb of their bodys recorded in human_parts.dmi.

I was going to go ahead and create a PR doing this, but I really do lack the expertise. I did a sloppy job with Predator limbs as is and don't want to messup this one. So I'm putting up a spriter request for help.

**Comment by ShadowDeath6** [comment] 2016-08-27 07:09
shadowpeople shouldn't be dismemberable as they're pretty much shadowlings, slime and jellypeople would just regrow limbs because they have slime jelly and that lets them reform stuff, I might get to coding an ability that makes them regrow limbs for some slime jelly, but that's for after the freeze

**Comment by Super3222** [comment] 2016-08-27 11:17
They have that Shadow. They just need sprites for their separate limbs.
I agree with the shadowpeople thing, they should have NODISMEMBER. And it actually only effects lesser shadowlings (the ones who are empowered by big ones).

**Comment by AndySok** [comment] 2016-08-27 19:32
I can help with sprites , just recolor human limbs and that's it

**Comment by AndySok** [comment] 2016-08-28 00:24
huh.
we already have shadowpeople's dismembered body parts sprite.

**Comment by ShadowDeath6** [comment] 2016-09-05 23:44
someone close this

**Closed** 2016-09-06 01:52 UTC
Labels: Bug, Sprite Request
