### ISSUE TITLE
vented gas event can crit

### ISSUE THREAD

**Issue by aphielanis** [yogstation13/yogstation#1713] opened 2017-01-25 13:06 UTC
the code broke or something and instead of just putting out space lube, cleaning solution, or at worst space drugs it actually crit me!

 I'm getting tired of fucked up shit. Pull the code until it's fixed please.

**Comment by Jc1469** [comment] 2017-01-25 13:37
https://github.com/yogstation13/yogstation/pull/1331

**Comment by drderp3635** [comment] 2017-01-25 14:45
Feature

**Comment by aphielanis** [comment] 2017-01-25 15:30
Oh, pull it it's stupid.

**Comment by drderp3635** [comment] 2017-01-25 15:33
Or just you know, don't stand in the fucking cloud of toxic gas like an idiot

**Comment by YogsMcree** [comment] 2017-01-25 15:39
Wah wah unrobust crit me wah. Suit sensors or don't be an idiot

**Comment by Time-Green** [comment] 2017-01-25 16:30
Dont try to inhale the clouds of gass coming from the fucking vents. I know it's hard, I always do it.
Anyway, this is a feature, and a fun one

**Comment by AdamElTablawy** [comment] 2017-01-25 16:48
yet another aphielansin shitpost

none of the chemicals in there can crit you unless you're a complete fucking retard and stand there AFK in the bar for an hour instead of going to medbay 

like you do every round

**Comment by aphielanis** [comment] 2017-01-26 14:01
Adam either act like an adult on github or don't come here.
 >
 >

 There is a chem that DOES CRIT with as little as second worth of exposure. I was running around the locker getting gear when I got hit with the cloud and I got barely to the front of the bridge before it crit me.

**Comment by drderp3635** [comment] 2017-01-26 19:26
Two points to be made here. 
1. If you got crit by these reagents you were either already hurt, or stood in the cloud for several seconds like a dumbass.
2. If you did stand in the gas like a dumbass/was near a vent that spewed you would still have enough time to call for help over the radio, or get to someone for help.
Sidenote: we need the I ded tag up in here

**Comment by AdamElTablawy** [comment] 2017-01-26 21:08
is there an 'i moron' tag as well

or perhaps an 'i make useless shitposts and get upset when people yell at me' tag

**Comment by Time-Green** [comment] 2017-01-29 19:47
"mine_salve","unholywater","mindbreaker","uranium","toxin","cleaner","carpotoxin","condensedcapsaicin","mushroomhallucinogen","lube","plantbgone","mutagen","charcoal","space_drugs","morphine","holywater","ethanol","mutetoxin","facid"
If I had to guess, you got carpotoxin.
Anyway, not a bug. I'd close it, but it's up to conversation if it should be removed.

**Comment by AdamElTablawy** [comment] 2017-01-30 15:03
carpotoxin doesn't kill that fast, he probably got a face full of facid and ran into the cloud repeatedly until he died

**Comment by Time-Green** [comment] 2017-01-30 19:12
Isn't carpotoxin the sleepy pen stuff? If he got about 200u in him, he is gonna be "crit" for a while

**Closed** 2017-09-10 04:54 UTC
Labels: Feature Request, i ded
