### ISSUE TITLE
Implanter UNUSABLE

### ISSUE THREAD

**Issue by 00aquir** [yogstation13/Yogstation#7527] opened 2020-01-06 18:37 UTC
Round 27132 or 27133, not sure because the server reverted back to a server restart in the next round.
I don't know what caused it but even after client restart, the mindshield implanter was not working, at all. When we could print a new implanter from protolathe, it worked, then after awhile when we came back, it also **didn't**. Always had to switch implanters..

**Comment by ToGWtF** [comment] 2020-05-24 19:56
Can fix in-game by putting implant back into empty implant case. dont know root cause

**Comment by redmoogle** [comment] 2021-01-12 13:45
I believe this was fixed by the pr that fixed gangs mindshield fuckery reopen if you see it again

**Closed as completed by redmoogle** 2021-01-12 13:45 UTC
Labels: Bug, Issue - Needs Confirmation, Issue - Low priority
