### ISSUE TITLE
Cant get favor in honkmother religion.

### ISSUE THREAD

**Issue by TosterIMC** [yogstation13/Yogstation#15054] opened 2022-07-29 07:24 UTC
### Severity

Inconvenience

### Short Description

I cant instert bananas to the altar.

### Reproduction

1.Chose the honkmother religion using the chaplain book on altar
2.Try to insert bananas
3.It doesnt accept bananas, no other way to gain favor

### Round ID

#42084

### BYOND Username

Tosterimc

**Comment by VaelophisNyx** [comment] 2022-08-04 20:49
being fixed

**Comment by MegaEmpirical** [comment] 2022-08-10 03:12
This appears to be a duplicate of https://github.com/yogstation13/Yogstation/issues/15050

**Closed as not planned** 2023-02-28 19:27 UTC
