### ISSUE TITLE
Fucking putting shit into the janidrope eats it

### ISSUE THREAD

**Issue by MegaEmpirical** [yogstation13/Yogstation#9232] opened 2020-07-16 18:42 UTC
Burn it all down. Fucking hate drobes.

Accidentally inserted my trash bag, it went in, no bag to take out.

**Comment by redmoogle** [comment] 2020-11-05 14:37
Tested

**Comment by adamsong** [comment] 2021-07-05 15:56
Duplicate of #9251

**Closed as completed by adamsong** 2021-07-05 15:56 UTC
Labels: Bug, Issue - Confirmed
