### ISSUE TITLE
Extendo Arm mutation may delete the arm you're using permanently

### ISSUE THREAD

**Issue by Sniblet** [yogstation13/Yogstation#11351] opened 2021-04-13 05:19 UTC
Issue reported from  Round ID: 34904 (Yogstation 13)

Reporting client version: 513.1542

I think it happens when you relax your arm while you're casting it

**Comment by adamsong** [comment] 2021-07-05 12:35
Unable to reproduce

**Comment by adamsong** [comment] 2021-07-20 16:51
Closing due to lack of confirmation or ability to reproduce

**Closed as completed by adamsong** 2021-07-20 16:51 UTC
Labels: Issue - Needs Confirmation
