### ISSUE TITLE
The crew monitoring console crashes your game.

### ISSUE THREAD

**Issue by Zostroll** [yogstation13/yogstation#2411] opened 2017-07-22 05:58 UTC
It is impossible to check the crew monitoring console on high-pop cause it **will** crash your game I remember it working before the rebase but it has been and issue for more than a year and no-one has done anything about it.

**Comment by Cruix** [comment] 2017-07-22 14:36
Dupe of #654

**Closed by Cruix** 2017-07-22 14:36 UTC

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment] 2017-07-22 16:33
How about get this fixed instead of closing with the reason of "Duplicate of a year old issue nobody will ever see again"?

**Comment by Cruix** [comment] 2017-07-22 20:08
It is still in the tracker, and this issue is not significantly more detailed or helpful than the issue that already exists. I personally have attempted to fix this bug at least once, and determined that the time investment would not be worth it compared to other work I could be doing. If you believe that this issue is truly urgent and needs to be resolved, you have a few options.

1. Gather data and create a more useful issue, asking for the old one to be closed.

2. Personally contact coders in game or on discord and compel them to work on it. All of our coders contribute to the codebase for free and are not obligated to do so, but you might be able to convince them to spent their time debugging and fixing this.

3. Learn how to write code in byond and fix it yourself. Here are some links that might be helpful in this regard:
http://www.byond.com/docs/guide/
http://www.byond.com/docs/ref/
https://forums.yogstation.net/index.php?threads/guide-to-git-or-in-other-words-how-to-create-features-on-the-github.13036/
https://kiwiirc.com/client/irc.rizon.net/coderbus
