### ISSUE TITLE
Defibs for Medical borgs

### ISSUE THREAD

**Issue by The-clown-known-as-Pepe** [yogstation13/yogstation#1787] opened 2017-02-09 18:09 UTC
Either as upgrade or standard equipement.

Syndie medborgs already have them so I don't think it'll be too hard.

**Comment by Genesis720** [comment] 2017-02-09 18:10
I support this. Should come with a high power use though. Maybe 500+

**Comment by ShadowDeath6** [comment] 2017-02-10 02:40
it's on my backlog and also a dupe of like 3 other issues

**Closed by ShadowDeath6** 2017-02-10 02:40 UTC
