### ISSUE TITLE
LOOC keeps turning itself off

### ISSUE THREAD

**Issue by Sir-Lagsalot** [yogstation13/Yogstation#6772] opened 2019-09-29 11:14 UTC
Issue reported from  Round ID: 25655 (Yogstation 13)

Reporting client version: 512.1467

Periodically, for seemingly no reason, my LOOC will disable itself. This happens every couple rounds. Additionally, under the "settings" tab at the top of my window, the "Show/Hide LOOC" option will not have changed. If it had the checkmark next to it before it was disabled, it will still be there afterwards. Honestly, LOOC should be enabled by default anyway, it kinda defeats the purpose to have it off.

**Comment by MegaEmpirical** [comment] 2019-09-29 20:34
Tell me more about these check marks, I don't have them.

**Comment by oklews** [comment] 2019-10-03 18:24
While i have no idea about what he means with check marks, Looc auto-disabling was a glowing brain move

**Comment by GenericDM** [comment] 2019-10-20 04:03
duplicate of #6298

**Closed as completed** 2019-10-21 01:26 UTC
Labels: Bug

**Comment by Sir-Lagsalot** [comment] 2019-10-23 22:22
![image](https://user-images.githubusercontent.com/52263717/67438615-02be5780-f5c2-11e9-8944-13f539acb8df.png)
These checkmarks
