### ISSUE TITLE
Play-Midi Verb Request.

### ISSUE THREAD

**Issue by R3DGL4R3** [yogstation13/yogstation#392] opened 2016-07-20 11:42 UTC
What's Wrong:Admins and PAs are still lacking the ability to play music despite us having an entirely new host that can handle decently sized midis.

Solution:Give Admins or at least PAs a "Play-Midi" verb.Unlike global sound this would be restricted to the midi file type,and have a file size limit,albeit a fair one.

**Comment by fizzle7** [comment] 2016-07-20 19:06
The problem is you have to include the music with the client which makes it huge because you can't stream musi through byond yet. Javascript will make that possible so when I'm done with all this I'll look into a framework for that, but if anyone wants to try it, go ahead.

**Comment by GrayRachnid** [comment] 2016-07-20 22:31
This is not a coding issue, this is an issue you have to bring up with the council.

There is also already a file size limit on midis.

**Comment by fizzle7** [comment] 2016-07-20 22:36
It's very much a coding issue, it's both.

**Comment by Kmc2000** [comment] 2016-07-20 23:45
we have the capability to play sounds already

Council restricted it for whatever reason

Pester them

**Comment by fizzle7** [comment] 2016-07-20 23:48
I don't think he means that since playing available midis takes no bandwith at all.

**Comment by SKR6DarkVoid** [comment] 2016-07-20 23:59
> we have the capability to play sounds already

Council restricted it for whatever reason

Pester them


El Senior Admin's have the verb, but its restricted to them and above, don't know why, more likely so a "trust" issue, and or "abuse" issue.  Bring it up to the council

**Comment by GrayRachnid** [comment] 2016-07-21 03:31
There is an admin +RANK that is called +SOUND. This gives admin ranks the ability to play sounds, as in MIDIs, OGGs, and what not. There is a file size limit on playing sounds. You are able to play sounds globally, and locally.

There is absolutely nothing with that setup, CODEWISE. Whether the rank is given to other admin ranks is thus a council issue.

So, where is the code problem in this?

>I don't think he means that since playing available midis takes no bandwith at all.

You're wrong.

**Comment by GrayRachnid** [comment] 2016-07-21 03:34
>John: Chip in for me
John: As a member of one of the most recent generations of council
John: It's not a coding issue.
John: And it will not be coded.

**Comment by Super3222** [comment] 2016-07-21 03:57
If you are asking for more permissions, that is something you bring up with the council or obtain the rank that can operate that verb yourself. I'll close this unless you have any more concerns, Red.

**Comment by R3DGL4R3** [comment] 2016-07-21 04:05
It's already been brought up with george.He told me he was all for it and to pester coders to get this specific idea implemented.
AKA get crackin neeeerds.

**Comment by R3DGL4R3** [comment] 2016-07-21 04:06
This would be less-abuseable and personally I don't think anyone below SA is ready for the unrestricted power of play global yet.Hence why I'm voicing it to begin with.

**Comment by R3DGL4R3** [comment] 2016-07-21 04:06
Oh

**Comment by R3DGL4R3** [comment] 2016-07-21 04:07
https://forums.yogstation.net/index.php?threads/overturn-admin-shuttle-coc-rule.11047/

**Comment by GrayRachnid** [comment] 2016-07-21 04:08
you know that not everyone can access that link right.

**Comment by R3DGL4R3** [comment] 2016-07-21 04:09
Oh yea,forgot that's in the admin discussions session.Piss.

**Comment by GrayRachnid** [comment] 2016-07-21 04:11
Let me quote myself.

>There is an admin +RANK that is called +SOUND. This gives admin ranks the ability to play sounds, as in MIDIs, OGGs, and what not. There is a file size limit on playing sounds. You are able to play sounds globally, and locally.

>There is absolutely nothing with that setup, CODEWISE. Whether the rank is given to other admin ranks is thus a council issue.

>So, where is the code problem in this?

**Comment by R3DGL4R3** [comment] 2016-07-21 04:19
If you wanna be legit about it there wouldn't be an actual code problem,but tossing +Sound down to lower ranks only to have it took away again when admin mcderp decides to play "Annoytheserver.ogg" and everyone files complaints and screams at the council doesn't seem all that productive.This is effectively a feature request for a lesser version of the +SOUND flag.

**Comment by GrayRachnid** [comment] 2016-07-21 04:23
OGGs almost have and can have the same size of a MIDI. They add for more sound variety when admins decide to play a sound, removing that just to be able to spam MIDIs defeats the point of giving admins the ability to play sounds in the first place. It's up to admins to police themselves on this matter, they're not players who sometimes need to be held back by game mechanics.

**Comment by R3DGL4R3** [comment] 2016-07-21 04:25
Ehhh,you've got a point.*Shrugs*

**Closed** 2016-07-21 04:31 UTC
