### ISSUE TITLE
 mapping issue lavaland base

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#14297] opened 2022-06-01 15:37 UTC
## Test Merges: 
Not Supplied / None
## Reproduction:
Description: the lavaland syndiacte base has power to its APCs but none of the equipment nor doors are powered, unsure if this has been reported before but it’s been awhile since it was broken and I’m tired of ahelps about it

 Submitted by: Cowbot (97736956326207488)

**Comment by ToasterBiome** [comment] 2022-06-03 03:34
Duplicate of https://github.com/yogstation13/Yogstation/issues/14262

**Closed as completed by ToasterBiome** 2022-06-03 03:34 UTC
