### ISSUE TITLE
Syndicate research outpost completely unpowered

### ISSUE THREAD

**Issue by nickd555** [yogstation13/Yogstation#14278] opened 2022-05-30 15:08 UTC
### Severity

Round Breaking

### Short Description

Syndicate research outpost machines/doors/etc were all unpowered despite 100% charge in its APC's

### Reproduction

1. Use ghost spawner menu to spawn as a Syndicate Bioweapons Researcher
2. Can't get out of the door of cryopod room because it wasn't powered
3. Shot way out of room
4. The only machines that worked outside of cryopod room were the lights, every other machine, door or item was unpowered
5. Checked APC's, they were 100% charged
6. Set APC's from automatic to charge machines, didn't change anything.

### Round ID

41214

### BYOND Username

isador555

**Comment by ToasterBiome** [comment] 2022-06-03 03:34
Duplicate of https://github.com/yogstation13/Yogstation/issues/14262

**Closed as completed by ToasterBiome** 2022-06-03 03:34 UTC
