### ISSUE TITLE
 Foam dart magazines are unable to collect darts

### ISSUE THREAD

**Issue by Yogbot-13** [yogstation13/Yogstation#21820] opened 2024-04-06 22:23 UTC
## Test Merges: 
Not Supplied / None
## Reproduction:
I came across this on an earlier round with an admin-spawned nerf gun, but confirmed it with a regular one. Whenever you attempt to collect a dart off the ground with any dart magazine, it throws "You fail to collect anything!" despite the dart coming straight from the magazine previously. No feedback is given when attempting to insert a dart manually, and it fails to insert, as well. The contents of the magazine don't appear to matter.

 Submitted by: .flikr (168806901457354753)

**Comment by AMyriad** [comment] 2024-04-06 22:30
duplicate of #21612
also will be fixed in #21807

**Closed as completed by AMyriad** 2024-04-06 22:30 UTC
Labels: Duplicate
