### ISSUE TITLE
Empath quirk prevents examining living people

### ISSUE THREAD

**Issue by Mqiib** [yogstation13/Yogstation#5293] opened 2019-04-28 00:30 UTC
Issue reported from  Round ID: 22785 (Yogstation 13)

Reporting client version: 512.1463

I took the neat new empath quirk and as it turns out, examining does absolutely nothing (no message appears) on living people. It still works on dead people and on self-examine.

**Comment by oklews** [comment] 2019-07-25 20:48
Still problem

**Comment by SomeguyManperson** [comment] 2019-09-22 08:49
this is likely caused by a runtime somewhere, I'll check it on a private server to see if it's still an issue/what causes it

**Comment by SomeguyManperson** [comment] 2019-09-22 09:00
ok currently empath *seems* to  be working, I tested it locally. If problems don't show up serverside I'll close this

**Comment by Mqiib** [comment] 2019-09-23 05:59
Now it just prevents you from seeing any damage on the person, even what you'd normally get from an examine. An improvement has been made though, you can see what they're wearing/holding.

**Closed as completed** 2020-10-10 07:25 UTC
Labels: Bug
