### ISSUE TITLE
viewport starts at widescreen proportions even if you don't have widescreen on

### ISSUE THREAD

**Issue by SomeguyManperson** [yogstation13/Yogstation#9789] opened 2020-09-25 00:05 UTC
usually occurs when first opening the game or after the server restarts iirc, means you have to manually reset your viewport to whatever size you want it/use fit-viewport verb to reset it to 15x15

**Comment by adamsong** [comment] 2021-07-05 14:48
Is this still an issue?

**Comment by 00aquir** [comment] 2021-07-05 16:35
yes

**Comment by 00aquir** [comment] 2021-07-05 16:37
> Is this still an issue?

Yes, I have to set it every time.

**Comment by adamsong** [comment] 2021-07-08 02:08
Does tgstation/tgstation#60079 fix this?

**Comment by Wayland-Smithy** [comment] 2021-07-08 02:44
Cool there was an open issue for this, just hiding downstream.

While I can't speak to the widescreen issue as that would appear to be working as intended upstream I do believe the forced "Fit Viewport" on (re)connecting part will be fixed by my PR mentioned just above.

> usually occurs when first opening the game or after the server restarts iirc

Yep exactly, and this issue open date lines up with the problematic line of code having appeared in May of 2020 too.

**Closed as completed** 2021-07-13 18:15 UTC
Labels: Bug, Issue - Confirmed
